export enum UsersTypes {
  ADD_USER = "ADD_USER",
  QUERY_USER = "QUERY_USER",
  FETCH_USERS = "FETCH_USERS",
  UPDATE_USER = "UPDATE_USER",
  REMOVE_USER = "REMOVE_USER",
  FETCH_USERS_ERROR = "FETCH_USERS_ERROR",
  FETCH_USERS_SUCCESSFUL = "FETCH_USERS_SUCCESSFUL",
}
